version: '3.7'

services:
  api:
    build:
      context: ./api
    volumes:
      - django_static:/static
      - django_media:/media
    env_file:
      - ./api/.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/datas/
    env_file:
      - ./db/.env

  nginx:
    restart: unless-stopped
    build: .
    volumes:
      - django_static:/app/django_files/static
      - django_media:/app/django_files/media
      - ./nginx/production:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  django_static:
  django_media:
  pg_data: