version: '3.7'

services:
  api:
    build:
      context: ./api
    volumes:
      - django_static:/static
      - django_media:/media
    env_file:
      - ./api/.env
    depends_on:
      - db
    ports:
      - 8000:8000
    command:
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:12.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/datas/
    env_file:
      - ./db/.env
    ports:
      - 5434:5432

  nginx:
    restart: always
    build: .
    volumes:
      - django_static:/app/django_files/static
      - django_media:/app/django_files/media
      - ./nginx/development:/etc/nginx/conf.d
    ports:
      - "84:80"
    depends_on:
      - api

volumes:
  django_static:
  django_media:
  pg_data: